server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      server:
        webflux:
          # ── Routes ────────────────────────────────────────────
          routes:
            - id: forum-service
              uri: lb://FORUM-SERVICE
              predicates:
                - Path=/api/forum/**

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**,/api/v1/settings/**,/api/v1/admin/security/**,/uploads/**

            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/v1/bookings/**,/api/v1/tickets/**

            - id: reclamation-service
              uri: lb://RECLAMATION-SERVICE
              predicates:
                - Path=/api/v1/reclamation/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**,/api/v1/refunds/**

            - id: fleet-service
              uri: lb://FLEET-SERVICE
              predicates:
                - Path=/api/v1/fleet/**

            - id: block-internal
              uri: no://op
              predicates:
                - Path=/internal/**
              filters:
                - SetStatus=403

          # ── Discovery ─────────────────────────────────────────
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

jwt:
  secret: ${JWT_SECRET:b7Kp9mR2xL4nW8vJ3hF6tY1sA5dG0qZwX}

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    gateway:
      enabled: true
  tracing:
    sampling:
      probability: 1.0